# Workflow for CI
name: Terraform CI

on:
  pull_request:
    branches:
      - staging
      
permissions:
  contents: read
  pull-requests: write # allow comment on PR
  
jobs:
  changes:
    runs-on: self-hosted # EC2 runner
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            terraform:
              - 'environments/stg/**'
              - 'environments/prd/**'
              - 'modules/**'
      - name: Comment when no Terraform changes
        if: steps.filter.outputs.terraform != 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform-plan
          message: |
            ## Terraform Plan Result
            No changes detected in `environments/stg/`, `environments/prd/` or modules/.  
            Skipping Terraform plan.

  terraform-ci:
    runs-on: self-hosted # EC2 runner
    needs: changes
    if: needs.changes.outputs.terraform == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Detect changed Terraform directories
        id: changed
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          filters: |
            stg:
              - 'environments/stg/**'

      - name: Collect changed directories
        id: collect
        run: |
          CHANGED_DIRS=""
          for file in ${{ steps.changed.outputs.stg_files }}; do
            DIR=$(dirname "$file")
            CHANGED_DIRS="$CHANGED_DIRS $(echo "$DIR" | cut -d'/' -f1-3)"
          done
          
          CHANGED_DIRS=$(echo "$CHANGED_DIRS" | tr ' ' '\n' | sort -u)
          echo "Detected Terraform directories:"
          echo "$CHANGED_DIRS"

          echo "dirs<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_DIRS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Terraform Validate + Plan
        id: tf
        run: |
          RESULT=""
          echo "${{ steps.collect.outputs.dirs }}" > dirs.txt
          mapfile -t DIRS < dirs.txt  # đọc từng dòng vào mảng DIRS

          for dir in "${DIRS[@]}"; do
            echo "---- Running in $dir ----"
            cd "$dir"

            terraform init -input=false
            terraform fmt -check
            terraform validate
            terraform plan -input=false -no-color -out=tfplan || true

            terraform show -no-color tfplan > plan.txt
            FULL_PLAN=$(cat plan.txt)

            RESULT="$RESULT\n\n### $dir\n\`\`\`\n$FULL_PLAN\n\`\`\`"
            cd - >/dev/null
          done

          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo -e "$RESULT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment plan on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: terraform-plan
          message: |
            ## Terraform Plan Result
            ${{ steps.tf.outputs.result }}
